#!/usr/local/Cellar/python/2.7.2/bin/python2.7

from os.path import abspath, dirname, join
import sys

from lib2to3 import main

sys.path.insert(0, abspath(join(dirname(__file__), "../")))


sys.exit(main("pep8ifier.fixes"))
